Check that all log files are readable in kolla-ansible check
The fluentd user needs to be able to read all log files in order to
process them. This change adds a check to the common role to check that
all log files under /var/log/kolla/ are readable by the fluentd user.

Change-Id: I2d0a6cde4c35c0c98aab9e688c584f24ac1dd229
Related-Bug: #1794472

diff --git a/ansible/roles/common/tasks/check.yml b/ansible/roles/common/tasks/check.yml
--- a/ansible/roles/common/tasks/check.yml
+++ b/ansible/roles/common/tasks/check.yml
@@ -1,1 +1,15 @@
 ---
+- name: Check that all log files are readable by fluentd
+  command: >-
+    docker exec fluentd
+    bash -c '
+        rc=0
+        for f in $(find /var/log/kolla/ -type f); do
+            if [[ ! -r $f ]]; then
+                echo "Cannot read $f"
+                rc=1
+            fi
+        done
+        exit $rc
+    '
+  changed_when: false
